### ISSUE TITLE
Can you please add a version for esp32-wroom-32? 

### ISSUE THREAD

**Issue by mosheliv** [bablokb/pcb-pico-en-control#1]
They are just much cheaper and for any practical purpose just as good for sensors.

**Comment by bablokb** [comment]
The ESP32-WROOM-32 is an old chip not recommended for newer designs. And "much" cheaper is something I would not agree with. The chip itself is much cheaper, but the difference in dev-board prices is not that high. Especially if you don't buy the cheapest stuff you can find on Ali.

BTW: you can use the existing PCB with any 3V3 MCU. You cannot just plug it into the device.

**Comment by mosheliv** [comment]
I am trying to use this to have a sensor monitoring soil moisture of a
plant once a day. As I'm thinking about 10+ sensors, the difference between
the cheap esp32 and the pico is substantial. Yes, i did realize i could use
it independently (and will, already ordered a few from jlbpcb, thank you
for making it so easy) but no harm in asking...
Cheap Esp32 is about 2.5$, pico wifi is about 10$.
Best regards and many thanks for the work you did!

**Comment by bablokb** [comment]
Yes, no problem. Designing it for a specific ESP32 breakout would not be much work, but I would have to know the exact pinout, have a sample dev-board and so on. But I am busy with other projects...

What I might do one day is redesign the board to be a bit more generic designed for wiring. I.e. with a single connector, all necessary pins on one side.

**Comment by mosheliv** [comment]
I think the most common amature board is the esp32-cam. It is very cheap
and reasonably powerful and has an okish camera and all for around $5.
However, it is notoriously bad as a battery operated device as it draws a
lot of current when idle/deep sleep and needs regulated voltage (thats the
greatest thing about your board - the regulator can be after the board!). i
will make some tests with the boards when the arrive and see if it works as
advertised on a breadboard.

**Comment by mosheliv** [comment]
Another question (and forgive me if its stupid as I'm a complete amature) :
why did you choose the enable pin and not a more general solution using
a IRLZ44N MOSFET to turn on the chip from zero? This should be even more
energy efficient, no?

**Comment by bablokb** [comment]
A valid question and I already have an alternative board for that: https://github.com/bablokb/pcb-pico-power-switch

Indeed, the regulator inside the Pico will draw about 75µA even when EN is pulled low. So my other board is more efficient (I measured something like 350nA in off-mode). Since the second board also uses a mosfet for reverse-power protection (instead of a schottky), the voltage drop is also lower.

But there is a use-case where this board is better: driving the EN pin also works when on USB-power. Also, you will find DC-DC converters with EN-pin, so you can also drive the power-source.

**Comment by mosheliv** [comment]
Ohhhh I wish i saw this before! Amazing, sent it to jlpcb...
Thank you AGAIN for making it so easy.
I saw that there is an esp32-c3. It's tiny but reasonably strong, very very
low power even when working and dirt cheap as smt component as it's risc v
so no amd royalties. It has limited io but for a single sensor it will do
nicely.
Was thinking of making the whole circuit (the one with the MOSFET) with the
processor on board but this is still far beyond my very basic abilities as
it needs antenna and other black magic stuff like voltage regulator. Will
give it a go anyways, perhaps will learn something while trying.

**Comment by bablokb** [comment]
Antennas are complicated and the regulator-stuff is also difficult. I am using the QT-Py ESP32-C3 from Adafruit, and the antenna they added really had problems. I removed the on-board antenna which just did not work and added an external one. This only shows how complicated things are.

Voltage regulators are also challenging. You can spoil everything here. I have an ESP32-S3 board from Adafruit which uses 18µA in deep-sleep, and an ESP32-S3 board from Waveshare which uses 1000µA.

**Comment by mosheliv** [comment]
Yes, the cheap esp32 are pretty horrible in deep sleep, hence my joy at
finding your circuit.... I ordered c3 super mini to check its deep sleep
current. If I can get the boards to work, I'll have under 10$ per node
moisture sensor and pir light/detection with wifi that are supposed to work
for years before battery needs to be changed and i can use 18650 because
the voltage regulator is after the mosfet. Hopefully everything will work
well.
